version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes: [ "mongo_data:/data/db" ]

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      MONGO_URI: "${MONGO_URI}"
      JWT_SECRET: "${JWT_SECRET}"
      NODE_ENV: "production"
      PORT: "${API_PORT:-4000}"
      FRONTEND_URL: "${FRONTEND_URL:-http://localhost:8080}"
    depends_on: [ mongo ]
    ports: [ "${API_PORT:-4000}:4000" ]
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on: [ api ]
    ports: [ "8080:80" ]
    restart: unless-stopped

volumes:
  mongo_data:
