services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    image: sit725-app:hd
    environment:
      PORT: "3000"
      MONGO_URI: "mongodb://mongo:27017/feedbackLense"  # use the service name
    ports:
      - "4000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
